export const team= [   
  {
    img: require('../assets/img/EllipseBigService.png'),
    name: 'Klara Ipsum',
    profession: 'desiner',
    about: 'Tincidunt lobortis feugiat vivamus at augue eget.Risus feugiat in ante metus dictum. Amet aliquam id diam maecenas.', 
    email: 'klara@gmail.com',
    icon: require('../assets/img/Ellipse (2).png'),    
  },
  {
    img: require('../assets/img/EllipseBigAbout.png'),
    name: 'Klara Ipsum',
    profession: 'desiner',
    about: 'Tincidunt lobortis feugiat vivamus at augue eget.Risus feugiat in ante metus dictum. Amet aliquam id diam maecenas.', 
    email: 'klara@gmail.com',
    icon: require('../assets/img/Ellipse (3).png'),    
  },
  {
    img: require('../assets/img/EllipseBig.png'),
    name: 'Klara Ipsum',
    profession: 'desiner',   
    about: 'Tincidunt lobortis feugiat vivamus at augue eget.Risus feugiat in ante metus dictum. Amet aliquam id diam maecenas.', 
    email: 'klara@gmail.com',
    icon: require('../assets/img/Ellipse (4).png'),    
  },
  {
    img: require('../assets/img/EllipseBigWork.png'),
    name: 'Klara Ipsum',
    profession: 'desiner',   
    about: 'Tincidunt lobortis feugiat vivamus at augue eget.Risus feugiat in ante metus dictum. Amet aliquam id diam maecenas.', 
    email: 'klara@gmail.com',
    icon: require('../assets/img/Ellipse (5).png'),    
  },
  {
    img: require('../assets/img/EllipseBigWork2.png'),
    name: 'Klara Ipsum',
    profession: 'desiner',   
    about: 'Tincidunt lobortis feugiat vivamus at augue eget.Risus feugiat in ante metus dictum. Amet aliquam id diam maecenas.', 
    email: 'klara@gmail.com',
    icon: require('../assets/img/Ellipse (6).png'),    
  },
  {
    img: require('../assets/img/EllipseBigWork3.png'),
    name: 'Klara Ipsum',
    profession: 'desiner',   
    about: 'Tincidunt lobortis feugiat vivamus at augue eget.Risus feugiat in ante metus dictum. Amet aliquam id diam maecenas.', 
    email: 'klara@gmail.com',
    icon: require('../assets/img/Ellipse (6).png'),    
  },
]
  
